# Generated by Django 4.1.2 on 2022-10-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('job', models.CharField(choices=[('DG', 'Directeur Générale'), ('DAF', 'Directeur Affaire Financière'), ('DT', 'Directeur Technique'), ('Ingénieur', 'Ingénieur'), ('Technicien', 'Technicien'), ('Commercial', 'Commercial')], default='Technicien', max_length=20)),
                ('phone_number', models.IntegerField()),
                ('leave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('possible', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=4)),
                ('comment', models.TextField(max_length=250)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employe', models.ManyToManyField(blank=True, to='home.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employe', models.ManyToManyField(blank=True, to='home.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250)),
                ('etat', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=4)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employe', models.ManyToManyField(blank=True, to='home.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Depannage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250)),
                ('etat', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employe', models.ManyToManyField(blank=True, to='home.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
            ],
        ),
    ]
