# Generated by Django 4.1.2 on 2022-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrait',
            name='reste',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=4),
        ),
    ]
