# Generated by Django 4.1.2 on 2022-10-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_retrait_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='jours',
            field=models.IntegerField(default=0),
        ),
    ]
