# Generated by Django 4.1.2 on 2022-10-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_employe_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='jours',
            field=models.IntegerField(default=0),
        ),
    ]
