# Generated by Django 4.1.2 on 2022-10-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employe_jours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='jours',
        ),
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('num_serie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('new', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('num_serie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('new', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
    ]
