# Generated by Django 4.1.3 on 2022-11-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_employe_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depannage',
            name='caractéristique',
            field=models.ImageField(blank=True, null=True, upload_to='caracteristique'),
        ),
        migrations.AlterField(
            model_name='depannage',
            name='employe',
            field=models.ManyToManyField(to='home.employe'),
        ),
        migrations.AlterField(
            model_name='depannage',
            name='mat',
            field=models.ImageField(blank=True, null=True, upload_to='mat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='employe',
            field=models.ManyToManyField(to='home.employe'),
        ),
    ]
