# Generated by Django 4.1.2 on 2022-10-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('job', models.CharField(choices=[('DG', 'Directeur Générale'), ('DAF', 'Directeur Affaire Financière'), ('DT', 'Directeur Technique'), ('Ingénieur', 'Ingénieur'), ('Technicien', 'Technicien'), ('Commercial', 'Commercial')], default='Technicien', max_length=40)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('conge', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
            ],
        ),
    ]
