# Generated by Django 4.1.2 on 2022-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_conge_conge_alter_conge_id_alter_employe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='leave',
            field=models.BooleanField(default=False),
        ),
    ]
